services:
  - type: web
    name: tiki-topple-online
    runtime: node
    plan: free
    region: singapore
    buildCommand: npm ci && npm run build
    startCommand: npm run server
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production

